import React from 'react';
import appLogo from './icons/mini-icon.svg';

export function BackButton({ onClick }) {
  return (
    <button className="btn-back" onClick={onClick} aria-label="Back">
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"/>
      </svg>
    </button>
  );
}

export function DownloadButton({ onClick, disabled, loading }) {
  return (
    <button className="btn-download" onClick={onClick} disabled={disabled || loading}>
      {loading ? <span className="spinner" /> : <span>DOWNLOAD</span>}
      {!loading && (
        <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path d="M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z"/>
        </svg>
      )}
    </button>
  );
}

export function LDTLogo() {
  return (
     <img src={appLogo} className="logo-icon" alt="Logo"/>
  );
}

export function InputRow({ value, onChange, placeholder, onConfirm, disabled }) {
  return (
    <div className="input-row">
      <input
        className="input-field"
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        disabled={disabled}
        onKeyDown={e => e.key === 'Enter' && onConfirm && onConfirm()}
      />
      <div className="confirm-row">
        <button className="btn-confirm" onClick={onConfirm} disabled={disabled}>
          CONFIRM
        </button>
      </div>
    </div>
  );
}

export function StatusMsg({ type, children }) {
  if (!children) return null;
  return <div className={`status-msg ${type}`}>{children}</div>;
}

export function LoadingOverlay({ text }) {
  return (
    <div className="loading-overlay">
      <div className="spinner" style={{ width: 40, height: 40, borderWidth: 4 }} />
      <div className="loading-text">{text || 'Working...'}</div>
    </div>
  );
}

export function QRScreen({ onBack }) {
  return (
    <div className="screen">
      <div className="header-row">
        <BackButton onClick={onBack} />
      </div>
      <div className="qr-container">
        <div className="qr-placeholder">
          {/* Placeholder QR - real QR comes from DepotDownloader on stdout */}
          <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
            <rect x="5" y="5" width="35" height="35" fill="none" stroke="#000" strokeWidth="3"/>
            <rect x="12" y="12" width="21" height="21" fill="#000"/>
            <rect x="60" y="5" width="35" height="35" fill="none" stroke="#000" strokeWidth="3"/>
            <rect x="67" y="12" width="21" height="21" fill="#000"/>
            <rect x="5" y="60" width="35" height="35" fill="none" stroke="#000" strokeWidth="3"/>
            <rect x="12" y="67" width="21" height="21" fill="#000"/>
            {/* Dots pattern */}
            {[20,30,40,50,60,70,80].map(x =>
              [20,30,40,50,60,70,80].map(y =>
                Math.random() > 0.5 ? (
                  <rect key={`${x}-${y}`} x={x} y={y} width="6" height="6" fill="#000"/>
                ) : null
              )
            )}
          </svg>
        </div>
        <p className="qr-label">
          Use the <a href="#">Steam Mobile App</a> to sign<br/>in via QR code
        </p>
        <p className="qr-label" style={{color:'#888', fontSize:'0.75rem'}}>
          QR code is generated by DepotDownloader in the terminal.<br/>
          This screen will advance automatically once authenticated.
        </p>
      </div>
    </div>
  );
}
