// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseForLCInstallation():Promise<string>;

export function BrowseForSteamFolder():Promise<string>;

export function CheckHasBepInEx(arg1:string):Promise<boolean>;

export function GetAssemblies():Promise<Array<main.AssemblyInfo>>;

export function GetDefaultSteamFolder():Promise<string>;

export function GetLCVersions():Promise<Array<main.LCVersionInfo>>;

export function InstallCompleteAssembly(arg1:number,arg2:string):Promise<void>;

export function InstallMod(arg1:string,arg2:string,arg3:number):Promise<void>;

export function InstallNewInstance(arg1:string,arg2:number,arg3:string):Promise<string>;

export function IsValidThunderstoreLink(arg1:string):Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function ParseThunderstoreLink(arg1:string):Promise<string>;

export function SetExistingInstallation(arg1:string,arg2:number,arg3:boolean):Promise<void>;
