// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForLCInstallation() {
  return window['go']['main']['App']['BrowseForLCInstallation']();
}

export function BrowseForSteamFolder() {
  return window['go']['main']['App']['BrowseForSteamFolder']();
}

export function CheckHasBepInEx(arg1) {
  return window['go']['main']['App']['CheckHasBepInEx'](arg1);
}

export function GetAssemblies() {
  return window['go']['main']['App']['GetAssemblies']();
}

export function GetDefaultSteamFolder() {
  return window['go']['main']['App']['GetDefaultSteamFolder']();
}

export function GetLCVersions() {
  return window['go']['main']['App']['GetLCVersions']();
}

export function InstallCompleteAssembly(arg1, arg2) {
  return window['go']['main']['App']['InstallCompleteAssembly'](arg1, arg2);
}

export function InstallMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallMod'](arg1, arg2, arg3);
}

export function InstallNewInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallNewInstance'](arg1, arg2, arg3);
}

export function IsValidThunderstoreLink(arg1) {
  return window['go']['main']['App']['IsValidThunderstoreLink'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ParseThunderstoreLink(arg1) {
  return window['go']['main']['App']['ParseThunderstoreLink'](arg1);
}

export function SetExistingInstallation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetExistingInstallation'](arg1, arg2, arg3);
}
